---
- name: Install NginX
  apt: name=nginx state=present

- name: Enable and start NginX service
  service: name=nginx state=started enabled=yes

- name: Configure NginX
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx
