---
- name: Add new GPG key for docker repository
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Add docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo debian-jessie main' state=present

- name: Install docker
  apt: name=docker-engine state=present update_cache=yes

- name: Install python-docker
  pip: name=docker-py version=1.7.0

- name: Enable and start docker service
  service: name=docker state=started enabled=yes
